[package]
name = "spaghettos_kernel_rs"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
crate-type = ["staticlib"]

[build]
target = "x86_64-unknown-none"
